
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # SECONDS
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3

PARTICLE_RADIUS = 2
PARTICLE_THRUST_COOLDOWN = 0.1
PARTICLE_THRUST_DEGREE_VARIANCE = 25
PARTICLE_THRUST_SPEED = 300

WEAPON_SWAP_DELAY = 2

PISTOL_FIRE_RATE = 0.3
PISTOL_DAMAGE = 10.0
PISTOL_SHOOT_SPEED = 800
PISTOL_SHOT_RADIUS = 7
PISTOL_ACCURACY = 0

SMG_FIRE_RATE = 0.05
SMG_DAMAGE = 0.7
SMG_SHOOT_SPEED = 380
SMG_SHOT_RADIUS = 1
SMG_ACCURACY = 13