
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # SECONDS
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3

PARTICLE_RADIUS = 2
PARTICLE_RADIUS_TRHUST = 3
PARTICLE_THRUST_COOLDOWN = 0.1
PARTICLE_THRUST_DEGREE_VARIANCE = 25
PARTICLE_THRUST_SPEED = 300
PARTICLE_ON_HIT_FADE = 1

WEAPON_SWAP_DELAY = 2

PISTOL_FIRE_RATE = 0.3
PISTOL_DAMAGE = 10.0
PISTOL_SHOOT_SPEED = 800
PISTOL_SHOT_RADIUS = 7
PISTOL_ACCURACY = 0

SMG_FIRE_RATE = 0.05
SMG_DAMAGE = 3
SMG_SHOOT_SPEED = 450
SMG_SHOT_RADIUS = 1
SMG_ACCURACY = 13

TOWER_TIMER_LENGTH = 60.0

GAME_DIRECTOR_SCREEN_SPAWN_CAP = 10
GAME_DIRECTOR_SCREEN_SPAWN_DIVIDING_FACTOR = 3
GAME_DIRECTOR_SPAWN_TIMER = 2