
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BORDER_KILL_ZONE_X = SCREEN_WIDTH // 2
BORDER_KILL_ZONE_Y = SCREEN_HEIGHT // 2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # SECONDS
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_COLOR = (255,0,0)
ASTEROID_BASE_HEALTH = 30
ASTEROID_BASE_EXP_DROP = 10

MELEE_RADIUS = 29
MELEE_SPEED = 80
MELEE_COLOR = (100, 255, 0)
MELEE_BASE_HEALTH = 40
MELEE_BASE_EXP_DROP = 30

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3
PLAYER_EXP_MAGNET = 60
PLAYER_EXP_REQUIRED_BASE = 100
PLAYER_EXP_MULTIPLIER_BASE = 0.099
PLAYER_EXP_MULTIPLIER_EXPO = 1.5

PLAYER_EXP_DISPLAY_POSITION_X = 0
PLAYER_EXP_DISPLAY_POSITION_Y = SCREEN_HEIGHT * 0.1
PLAYER_EXP_DISPLAY_LENGTH = 200
PLAYER_EXP_DISPLAY_HEIGHT = 5
PLAYER_EXP_DISPLAY_BORDER = 5
PLAYER_EXP_DISPLAY_BORDER_COLOR = (65,65,65)

EXP_HIT_BOX_RADIUS = 8
EXP_COLOR = (255, 255, 128)
EXP_SIZE_WIDTH = 20
EXP_SIZE_HEIGHT = 20
EXP_ROTATION_SPEED = 200
EXP_SPEED = 500

PARTICLE_RADIUS = 2
PARTICLE_RADIUS_TRHUST = 3
PARTICLE_THRUST_COOLDOWN = 0.1
PARTICLE_THRUST_DEGREE_VARIANCE = 25
PARTICLE_THRUST_SPEED = 300
PARTICLE_ON_HIT_FADE = 1
PARTICLE_ON_DEATH_SPEED = 20
PARTICLE_ON_DEATH_COLOR_ADJUSTMENT = 50

WEAPON_SWAP_DELAY = 2

PISTOL_FIRE_RATE = 0.3
PISTOL_DAMAGE = 10.0
PISTOL_SHOOT_SPEED = 800
PISTOL_SHOT_RADIUS = 7
PISTOL_ACCURACY = 1
PISTOL_PELLETS = 1

SMG_FIRE_RATE = 0.05
SMG_DAMAGE = 6
SMG_SHOOT_SPEED = 450
SMG_SHOT_RADIUS = 1
SMG_ACCURACY = 23
SMG_PELLETS = 1

SHOTGUN_FIRE_RATE = 0.6
SHOTGUN_DAMAGE = 7
SHOTGUN_SHOOT_SPEED = 500
SHOTGUN_SHOT_RADIUS = 2
SHOTGUN_ACCURACY = 45
SHOTGUN_PELLETS = 2

TOWER_TIMER_LENGTH = 15.0

GAME_DIRECTOR_SCREEN_SPAWN_CAP = 10
GAME_DIRECTOR_SCREEN_SPAWN_DIVIDING_FACTOR = 3
GAME_DIRECTOR_SPAWN_TIMER = 2
