##incase of small spelling error :)
COUNT = "count"
DESCRIPTION = "description"

RARITY = "rarity"
WHITE = "white"
WHITE_ODDS = 73.99
GREEN = "green"
GREEN_ODDS = 98.89
RED = "red"

ITEM_BOUCE_SCALE = 0.5
ITEM_BOUCE_SPEED = 10

ITEM_IMAGE_X_OFFSET = 25
ITEM_IMAGE_Y_OFFSET = 25

PLACE_HOLDER_IMAGE = "Assets/placeholder.png"

DUD_AIRSTRIKE_NAME = "dud airstrike"
DUD_AIRSTRIKE_DMG = 50
DUD_AIRSTRIKE_ODDS = 50
DUD_AIRSTRIKE_RADIUS = 100

THREADED_BARREL_NAME = "threaded barrel" 
THREADED_BARREL_VALUE = 1.2

EXTRA_GUNPOWDER_NAME = "extra gunpowder"
EXTRA_GUNPOWDER_RADIUS = 69

GHOST_LOADING_NAME = "ghost loading"
GHOST_LOADING_VALUE = 10

MAGNET_NAME = "magnet"
MAGNET_VALUE = 5

BANANA_MAG_NAME = "banana mag"
BANANA_MAG_VALUE = 3

POCKET_MISSLE_NAME = "Pocket Missle"
POCKET_MISSLE_DMG = 25
POCKET_MISSLE_ODDS = 22

ARMOR_CHIPPER_NAME = "Armor Chipper"
ARMOR_CHIPPER_THRESHOLD = 90
ARMOR_CHIPPER_VALUE = 1.44

SPEED_LOADER_NAME = "Speed Loader"
SPEED_LOADER_VALUE = 10

TRIGGER_FINGER_NAME = "Trigger Finger"
TRIGGER_FINGER_VALUE = 10

BLOOD_SUSTAINED_SHIELD_NAME = "Blood Sustained Shield"
BLOOD_SUSTAINED_SHIELD_VALUE = 2.5

ARMOR_PIERCING_ROUNDS_NAME = "Armor Piercing Rounds"
ARMOR_PIERCING_ROUNDS_VALUE = 1

GOO_GLIME_NAME = "Goo Glime"
GOO_GLIME_VALUE = 38

POCKET_SAND_NAME = "Pocket Sand"
POCKET_SAND_ODDS = 10
POCKET_SAND_DURATION = 0.6